import type { T } from '../i18n';

/**
 * What the home screen, packages and links need to know about each form, without loading the
 * forms themselves: their questions and PDF fillers load only when a form is opened (load.ts).
 * catalog.test.ts checks this list against the form definitions, so keep them in sync.
 */
export interface FormMeta {
  id: string;
  number: string;
  title: T;
  summary: T;
  minutes: number;
  edition: string;
  /** Whether the form's checklist has a USCIS fee (links the fee calculator). */
  fee: boolean;
}

export const catalog: FormMeta[] = [
  {
    id: 'i-765',
    number: 'I-765',
    title: { es: "Solicitud de permiso de trabajo", en: "Application for Employment Authorization" },
    summary: { es: "Pida o renueve su permiso de trabajo (EAD): asilo, TPS, parole, DACA, ajuste de estatus y más.", en: "Apply for or renew your work permit (EAD): asylum, TPS, parole, DACA, adjustment of status and more." },
    minutes: 20,
    edition: '08/21/25',
    fee: true,
  },
  {
    id: 'i-765ws',
    number: 'I-765WS',
    title: { es: "Hoja de trabajo del Formulario I-765", en: "Form I-765 Worksheet" },
    summary: { es: "Muestre su necesidad económica de trabajar: ingresos, gastos y bienes. Va con el I-765 de DACA ((c)(33)) o acción diferida ((c)(14)).", en: "Show your economic need to work: income, expenses and assets. Goes with a DACA ((c)(33)) or deferred action ((c)(14)) Form I-765." },
    minutes: 10,
    edition: '08/21/25',
    fee: false,
  },
  {
    id: 'i-821d',
    number: 'I-821D',
    title: { es: "DACA (Acción Diferida para los Llegados en la Infancia)", en: "DACA (Deferred Action for Childhood Arrivals)" },
    summary: { es: "Renueve su DACA (o pida DACA por primera vez). Se presenta junto con el I-765 para el permiso de trabajo.", en: "Renew your DACA (or request it for the first time). Filed together with Form I-765 for the work permit." },
    minutes: 30,
    edition: '01/20/25',
    fee: false,
  },
  {
    id: 'i-821',
    number: 'I-821',
    title: { es: "TPS (Estatus de Protección Temporal)", en: "TPS (Temporary Protected Status)" },
    summary: { es: "Pida o vuelva a registrar su TPS si es de un país designado (por ejemplo, Venezuela, Honduras, El Salvador o Haití). Va junto con el I-765.", en: "Apply for or re-register your TPS if you are from a designated country (for example Venezuela, Honduras, El Salvador or Haiti). Filed with Form I-765." },
    minutes: 45,
    edition: '01/20/25',
    fee: true,
  },
  {
    id: 'i-130',
    number: 'I-130',
    title: { es: "Petición para un familiar", en: "Petition for Alien Relative" },
    summary: { es: "Si es ciudadano/a o residente permanente, pida la residencia para su cónyuge, hijo/a, padre, madre o hermano/a.", en: "If you are a U.S. citizen or permanent resident, petition for your spouse, child, parent or sibling to become a resident." },
    minutes: 60,
    edition: '04/01/24',
    fee: true,
  },
  {
    id: 'i-130a',
    number: 'I-130A',
    title: { es: "Información del cónyuge beneficiario", en: "Supplemental Information for Spouse Beneficiary" },
    summary: { es: "Lo llena el esposo o la esposa por quien se presenta un I-130. Va junto con el I-130.", en: "Filled in by the husband or wife an I-130 is filed for. It goes with the I-130." },
    minutes: 15,
    edition: '04/01/24',
    fee: false,
  },
  {
    id: 'i-129f',
    number: 'I-129F',
    title: { es: "Petición para prometido/a (visa K-1)", en: "Petition for fiancé(e) (K-1 visa)" },
    summary: { es: "El ciudadano de EE.UU. pide la visa para que su prometido/a venga a casarse (o su cónyuge, con la K-3).", en: "The U.S. citizen asks for a visa so their fiancé(e) can come to marry (or their spouse, with the K-3)." },
    minutes: 60,
    edition: '01/20/25',
    fee: true,
  },
  {
    id: 'i-485',
    number: 'I-485',
    title: { es: "Solicitud de residencia permanente (ajuste de estatus)", en: "Application to Register Permanent Residence or Adjust Status" },
    summary: { es: "Pida la green card desde dentro de EE.UU. si ya tiene una petición (I-130 u otra) o una categoría que lo permita.", en: "Apply for a green card from inside the U.S. if you have a petition (I-130 or other) or a category that allows it." },
    minutes: 75,
    edition: '09/18/26',
    fee: true,
  },
  {
    id: 'i-485supa',
    number: 'I-485 Supplement A',
    title: { es: "Suplemento A del I-485: ajuste de estatus bajo la sección 245(i)", en: "Supplement A to Form I-485, Adjustment of Status Under Section 245(i)" },
    summary: { es: "Se presenta con el I-485 si pide la green card gracias a una petición o certificación laboral presentada el 30 de abril de 2001 o antes.", en: "Filed with Form I-485 if you seek a green card based on a petition or labor certification filed on or before April 30, 2001." },
    minutes: 15,
    edition: '09/18/26',
    fee: true,
  },
  {
    id: 'i-131',
    number: 'I-131',
    title: { es: "Permiso de viaje", en: "Travel document" },
    summary: { es: "Pida un documento de viaje (advance parole, permiso de reingreso, documento de refugiado o de TPS) o parole: desde fuera de EE.UU., parole in place o re-parole.", en: "Ask for a travel document (advance parole, reentry permit, refugee or TPS travel document) or parole: from abroad, parole in place or re-parole." },
    minutes: 25,
    edition: '01/20/25',
    fee: true,
  },
  {
    id: 'i-131a',
    number: 'I-131A',
    title: { es: "Documento para volver a EE.UU. (residentes en el extranjero)", en: "Travel Document (Carrier Documentation)" },
    summary: { es: "Para residentes permanentes que están fuera de EE.UU. y perdieron su green card (o se les dañó o venció), y necesitan un documento para que la aerolínea los deje abordar de regreso.", en: "For permanent residents abroad whose green card was lost, stolen, destroyed, damaged or expired, who need a document so the airline lets them board back to the U.S." },
    minutes: 15,
    edition: '01/20/25',
    fee: true,
  },
  {
    id: 'i-864',
    number: 'I-864',
    title: { es: "Declaración de patrocinio económico", en: "Affidavit of Support" },
    summary: { es: "El patrocinador (quien presentó el I-130 o un copatrocinador) demuestra que puede mantener al inmigrante.", en: "The sponsor (who filed the I-130, or a joint sponsor) shows they can support the immigrant." },
    minutes: 30,
    edition: '08/24/26',
    fee: false,
  },
  {
    id: 'i-864ez',
    number: 'I-864EZ',
    title: { es: "Declaración de patrocinio económico (versión corta)", en: "Affidavit of Support (short form)" },
    summary: { es: "La versión corta del I-864: para el peticionario que patrocina a una sola persona con sus propios ingresos de W-2.", en: "The short version of Form I-864: for a petitioner sponsoring one person with their own W-2 income." },
    minutes: 15,
    edition: '08/24/26',
    fee: false,
  },
  {
    id: 'i-864a',
    number: 'I-864A',
    title: { es: "Contrato entre el patrocinador y un familiar del hogar", en: "Contract Between Sponsor and Household Member" },
    summary: { es: "Un familiar que vive con el patrocinador suma sus ingresos al I-864. Lo llenan juntos.", en: "A relative who lives with the sponsor adds their income to the I-864. They fill it in together." },
    minutes: 20,
    edition: '08/24/26',
    fee: false,
  },
  {
    id: 'i-865',
    number: 'I-865',
    title: { es: "Aviso de cambio de dirección del patrocinador", en: "Sponsor's Notice of Change of Address" },
    summary: { es: "Si firmó un I-864 (declaración de patrocinio) y se mudó, avise a USCIS su nueva dirección dentro de 30 días.", en: "If you signed Form I-864 (Affidavit of Support) and moved, tell USCIS your new address within 30 days." },
    minutes: 10,
    edition: '11/10/20',
    fee: false,
  },
  {
    id: 'i-751',
    number: 'I-751',
    title: { es: "Quitar las condiciones de la residencia", en: "Remove conditions on residence" },
    summary: { es: "Para residentes condicionales por matrimonio (tarjeta de 2 años): pida la residencia de 10 años en los 90 días antes de que venza.", en: "For conditional residents through marriage (2-year card): ask for the 10-year card within 90 days before it expires." },
    minutes: 40,
    edition: '04/01/24',
    fee: true,
  },
  {
    id: 'i-90',
    number: 'I-90',
    title: { es: "Renovar o reemplazar la green card", en: "Renew or replace your green card" },
    summary: { es: "Para residentes permanentes cuya tarjeta venció, está por vencer, se perdió, se dañó o tiene datos que cambiar.", en: "For permanent residents whose card expired, is about to expire, was lost or damaged, or needs updated information." },
    minutes: 15,
    edition: '01/20/25',
    fee: true,
  },
  {
    id: 'ar-11',
    number: 'AR-11',
    title: { es: "Cambio de dirección", en: "Change of address" },
    summary: { es: "Avise a USCIS que se mudó. Es obligatorio dentro de los 10 días siguientes a la mudanza.", en: "Tell USCIS you moved. It is required within 10 days of moving." },
    minutes: 5,
    edition: '11/02/22',
    fee: false,
  },
  {
    id: 'eoir-33',
    number: 'EOIR-33/IC',
    title: { es: "Cambio de dirección para la corte de inmigración", en: "Change of address for the immigration court" },
    summary: { es: "Si tiene un caso en corte de inmigración, avise a la corte su nueva dirección o teléfono dentro de 5 días hábiles.", en: "If you have a case in immigration court, tell the court your new address or phone within 5 working days." },
    minutes: 10,
    edition: 'Feb. 2026',
    fee: false,
  },
  {
    id: 'i-912',
    number: 'I-912',
    title: { es: "Solicitud de exención de tarifa", en: "Request for Fee Waiver" },
    summary: { es: "Pida que USCIS no le cobre la tarifa si recibe beneficios públicos, gana poco o pasa por dificultades económicas.", en: "Ask USCIS to waive the filing fee if you receive public benefits, have a low income or face financial hardship." },
    minutes: 25,
    edition: '07/22/25',
    fee: false,
  },
  {
    id: 'i-134',
    number: 'I-134',
    title: { es: "Declaración de apoyo económico", en: "Declaration of Financial Support" },
    summary: { es: "Una persona en EE.UU. declara que puede mantener a alguien durante una estadía temporal (algunas visas y permisos de parole).", en: "Someone in the U.S. declares they can financially support a person during a temporary stay (some visas and parole requests)." },
    minutes: 25,
    edition: '01/20/25',
    fee: false,
  },
  {
    id: 'i-589',
    number: 'I-589',
    title: { es: "Solicitud de asilo y de suspensión de deportación", en: "Application for Asylum and for Withholding of Removal" },
    summary: { es: "Pida asilo si teme regresar a su país por su raza, religión, nacionalidad, opinión política o grupo social. Hay que presentarla dentro de un año de su llegada.", en: "Apply for asylum if you fear returning to your country because of your race, religion, nationality, political opinion or social group. It must be filed within one year of arrival." },
    minutes: 90,
    edition: '07/28/26',
    fee: true,
  },
  {
    id: 'i-730',
    number: 'I-730',
    title: { es: "Petición de familiar de refugiado o asilado", en: "Refugee/Asylee Relative Petition" },
    summary: { es: "Si recibió asilo o refugio, pida que su cónyuge o sus hijos solteros menores de 21 reciban el mismo estatus.", en: "If you were granted asylum or refugee status, ask for your spouse or unmarried children under 21 to get the same status." },
    minutes: 40,
    edition: '01/20/25',
    fee: false,
  },
  {
    id: 'i-601a',
    number: 'I-601A',
    title: { es: "Perdón provisional por presencia ilegal", en: "Provisional Unlawful Presence Waiver" },
    summary: { es: "Pida perdón por haber estado sin permiso en EE.UU. antes de salir a su entrevista de visa en el consulado, para no quedar fuera del país 3 o 10 años.", en: "Ask to forgive time spent in the U.S. without status before leaving for your consular visa interview, so you are not barred from returning for 3 or 10 years." },
    minutes: 45,
    edition: '01/20/25',
    fee: true,
  },
  {
    id: 'i-601',
    number: 'I-601',
    title: { es: "Perdón de causas de inadmisibilidad", en: "Application for Waiver of Grounds of Inadmissibility" },
    summary: { es: "Pida perdón por algo que le impide recibir la residencia, una visa o el TPS: presencia ilegal, ciertos delitos, fraude migratorio, salud y otras causas.", en: "Ask to forgive something that bars you from a green card, a visa or TPS: unlawful presence, certain crimes, immigration fraud, health and other grounds." },
    minutes: 60,
    edition: '01/20/25',
    fee: true,
  },
  {
    id: 'i-212',
    number: 'I-212',
    title: { es: "Permiso para volver a pedir entrada después de una deportación", en: "Permission to Reapply for Admission After Deportation or Removal" },
    summary: { es: "Pida permiso para volver a solicitar entrada a EE.UU. antes de que termine el castigo por una deportación o por haber entrado sin permiso después de una.", en: "Ask for permission to apply again for admission to the U.S. before the bar from a deportation, or from an illegal re-entry after one, runs out." },
    minutes: 40,
    edition: '01/20/25',
    fee: true,
  },
  {
    id: 'i-918',
    number: 'I-918',
    title: { es: "Petición de visa U (víctimas de delitos)", en: "Petition for U Nonimmigrant Status" },
    summary: { es: "Pida la visa U si fue víctima de un delito grave en EE.UU., sufrió daño por él y ayudó a la policía o a la fiscalía.", en: "Ask for U nonimmigrant status if you were the victim of a qualifying crime in the U.S., were harmed by it and helped the police or prosecutors." },
    minutes: 50,
    edition: '01/20/25',
    fee: false,
  },
  {
    id: 'i-918supa',
    number: 'I-918 Supplement A',
    title: { es: "Suplemento A: visa U para un familiar", en: "Supplement A, Petition for Qualifying Family Member of U-1 Recipient" },
    summary: { es: "Si usted pide o tiene la visa U, pida que su esposo/a, hijos (y si es menor de 21, padres y hermanos) también la reciban. Uno por familiar.", en: "If you are seeking or have a U visa, ask for your spouse, children (and if you are under 21, parents and siblings) to receive it too. One per family member." },
    minutes: 35,
    edition: '01/20/25',
    fee: false,
  },
  {
    id: 'i-914',
    number: 'I-914',
    title: { es: "Solicitud de visa T (víctimas de trata de personas)", en: "Application for T Nonimmigrant Status" },
    summary: { es: "Pida la visa T si fue víctima de trata de personas (trabajo forzado o sexo comercial obligado) y está en EE.UU. por esa razón.", en: "Ask for T nonimmigrant status if you were a victim of human trafficking (forced labor or commercial sex) and are in the U.S. because of it." },
    minutes: 50,
    edition: '01/20/25',
    fee: false,
  },
  {
    id: 'i-914supa',
    number: 'I-914 Supplement A',
    title: { es: "Visa T para un familiar (Suplemento A del I-914)", en: "Application for Derivative T Nonimmigrant Status (Form I-914, Supplement A)" },
    summary: { es: "Si usted pidió o tiene la visa T, incluya a su esposo/a, hijos u otros familiares que pueden recibirla con usted. Un suplemento por cada familiar.", en: "If you applied for or hold T status, include your spouse, children or other eligible relatives. One supplement per family member." },
    minutes: 35,
    edition: '01/20/25',
    fee: false,
  },
  {
    id: 'i-360',
    number: 'I-360',
    title: { es: "Petición de amerasiático(a), viudo(a) o inmigrante especial", en: "Petition for Amerasian, Widow(er), or Special Immigrant" },
    summary: { es: "Pida la residencia como viudo(a) de un ciudadano, por VAWA, como joven con orden de una corte juvenil (SIJ), trabajador religioso, amerasiático(a), traductor o empleado afgano o iraquí, y otras categorías especiales, para usted o para un familiar.", en: "Petition as the widow(er) of a U.S. citizen, under VAWA, as a young person with a juvenile court order (SIJ), religious worker, Amerasian, Afghan or Iraqi translator or employee, and other special immigrant classifications, for yourself or a family member." },
    minutes: 45,
    edition: '01/20/25',
    fee: true,
  },
  {
    id: 'i-290b',
    number: 'I-290B',
    title: { es: "Aviso de apelación o moción", en: "Notice of Appeal or Motion" },
    summary: { es: "Pida que se revise una decisión negativa de USCIS: una apelación ante la AAO o una moción para reabrir o reconsiderar el caso.", en: "Ask for review of an unfavorable USCIS decision: an appeal to the AAO or a motion to reopen or reconsider the case." },
    minutes: 25,
    edition: '05/31/24',
    fee: true,
  },
  {
    id: 'i-539',
    number: 'I-539',
    title: { es: "Extender o cambiar su estatus de no inmigrante", en: "Application to Extend/Change Nonimmigrant Status" },
    summary: { es: "Pida quedarse más tiempo en EE.UU. con su visa actual (turista, estudiante, dependiente), cambiar a otro estatus temporal o recuperar su estatus de estudiante.", en: "Ask to stay longer in the U.S. in your current status (visitor, student, dependent), change to another temporary status, or be reinstated to student status." },
    minutes: 25,
    edition: '08/28/24',
    fee: true,
  },
  {
    id: 'i-539a',
    number: 'I-539A',
    title: { es: "Información adicional de un familiar para el I-539", en: "Supplemental Information for Application to Extend/Change Nonimmigrant Status" },
    summary: { es: "Un formulario por cada esposo/a o hijo/a que va incluido en el I-539 del solicitante principal para extender o cambiar su estatus.", en: "One form for each spouse or child included in the principal applicant’s Form I-539 to extend or change status." },
    minutes: 15,
    edition: '08/28/24',
    fee: false,
  },
  {
    id: 'i-102',
    number: 'I-102',
    title: { es: "Solicitud de reemplazo o primer registro de llegada y salida (I-94)", en: "Application for Replacement/Initial Nonimmigrant Arrival-Departure Document" },
    summary: { es: "Pida un I-94 nuevo si el suyo se perdió, se lo robaron, se dañó, nunca se lo dieron o USCIS lo emitió con un error.", en: "Ask for a new I-94 if yours was lost, stolen or damaged, was never issued, or was issued by USCIS with an error." },
    minutes: 15,
    edition: '04/01/24',
    fee: true,
  },
  {
    id: 'i-824',
    number: 'I-824',
    title: { es: "Acción sobre una solicitud o petición aprobada", en: "Application for Action on an Approved Application or Petition" },
    summary: { es: "Pida un duplicado del aviso de aprobación, que avisen a otro consulado, o que su cónyuge e hijos lo sigan después de hacerse residente.", en: "Ask for a duplicate approval notice, for a different consulate to be notified, or for your spouse and children to follow to join you after you became a resident." },
    minutes: 15,
    edition: '04/01/24',
    fee: true,
  },
  {
    id: 'i-407',
    number: 'I-407',
    title: { es: "Registro de abandono de la residencia permanente", en: "Record of Abandonment of Lawful Permanent Resident Status" },
    summary: { es: "Renuncie de forma voluntaria y permanente a su green card, por ejemplo si ya vive en otro país y no piensa volver.", en: "Voluntarily and permanently give up your green card, for example if you now live in another country and do not plan to return." },
    minutes: 10,
    edition: '09/25/24',
    fee: false,
  },
  {
    id: 'g-1145',
    number: 'G-1145',
    title: { es: "Aviso electrónico de aceptación", en: "e-Notification of Application/Petition Acceptance" },
    summary: { es: "Reciba un correo o mensaje de texto con su número de recibo cuando USCIS acepte su solicitud enviada por correo.", en: "Get an email or text message with your receipt number when USCIS accepts the application you mailed." },
    minutes: 2,
    edition: '09/26/14',
    fee: false,
  },
  {
    id: 'n-400',
    number: 'N-400',
    title: { es: "Solicitud de ciudadanía", en: "Application for Naturalization" },
    summary: { es: "Hágase ciudadano/a de EE.UU. si es residente permanente desde hace 5 años (3 si está casado/a con un ciudadano).", en: "Become a U.S. citizen if you have been a permanent resident for 5 years (3 if married to a U.S. citizen)." },
    minutes: 60,
    edition: '01/20/25',
    fee: true,
  },
  {
    id: 'n-336',
    number: 'N-336',
    title: { es: "Audiencia sobre la negación de su ciudadanía", en: "Request for a Hearing on a Decision in Naturalization Proceedings" },
    summary: { es: "Pida que otro oficial de USCIS revise su caso si le negaron el N-400 (la solicitud de ciudadanía).", en: "Ask another USCIS officer to review your case if your N-400 (citizenship application) was denied." },
    minutes: 25,
    edition: '04/01/24',
    fee: true,
  },
  {
    id: 'n-600',
    number: 'N-600',
    title: { es: "Solicitud de certificado de ciudadanía", en: "Application for Certificate of Citizenship" },
    summary: { es: "Para hijos de ciudadanos que ya son ciudadanos (por nacer de padre o madre ciudadano o por la naturalización de sus padres) y quieren el certificado que lo prueba.", en: "For children of citizens who are already citizens (born to a citizen parent or through their parents’ naturalization) and want the certificate that proves it." },
    minutes: 40,
    edition: '01/20/25',
    fee: true,
  },
  {
    id: 'n-565',
    number: 'N-565',
    title: { es: "Reemplazo de certificado de naturalización o ciudadanía", en: "Application for Replacement Naturalization/Citizenship Document" },
    summary: { es: "Pida un nuevo certificado de naturalización o de ciudadanía si se le perdió, se dañó, tiene un error o cambió su nombre.", en: "Request a new naturalization or citizenship certificate if yours was lost, damaged, has an error, or your name changed." },
    minutes: 15,
    edition: '02/27/25',
    fee: true,
  },
];

export const metaById = (id: string): FormMeta | null => catalog.find((f) => f.id === id) ?? null;
