import type { Field, FormDefinition, Option, Question } from './types';
import type { T } from '../i18n';
import { all, anyAddress, date, is, nameFields, num, sexField, yesNo } from './helpers';
import { flaggedI485, P9_GROUPS, P9_ITEMS, toYesNoItems } from './i485Part9';

// Questions follow USCIS Form I-485, Application to Register Permanent Residence or Adjust Status,
// edition 09/18/26. `formRef` gives the part, item number and the form's own English wording.
// src/pdf/i485Pdf.ts maps the answers onto that edition's fields; Part 9 lives in i485Part9.ts.

export const I485_EDITION = '09/18/26';

const usAddress = (prefix: string, ref: string, careOf: boolean): Field[] => [
  ...(careOf ? [{ id: `${prefix}.careOf`, type: 'text', label: { es: 'A cargo de (si recibe correo en casa de otra persona)', en: 'In care of' }, formRef: `${ref} · In Care Of Name`, maxLength: 34 } as Field] : []),
  { id: `${prefix}.street`, type: 'text', required: true, label: { es: 'Número y calle', en: 'Street number and name' }, formRef: `${ref} · Street Number and Name`, maxLength: 34, placeholder: '1234 Main St' },
  { id: `${prefix}.unit`, type: 'unit', label: { es: 'Apartamento, suite o piso', en: 'Apartment, suite or floor' }, formRef: `${ref} · Apt. / Ste. / Flr.`, placeholder: 'Apt 4B' },
  { id: `${prefix}.city`, type: 'text', required: true, label: { es: 'Ciudad', en: 'City or town' }, formRef: `${ref} · City or Town`, maxLength: 20 },
  { id: `${prefix}.state`, type: 'state', required: true, label: { es: 'Estado', en: 'State' }, formRef: `${ref} · State`, placeholder: 'CA' },
  { id: `${prefix}.zip`, type: 'zip', required: true, label: { es: 'Código postal (ZIP)', en: 'ZIP code' }, formRef: `${ref} · ZIP Code`, placeholder: '90210' },
];

const legal: Question['notice'] = {
  tone: 'legal',
  title: { es: 'Esto no es asesoría legal', en: 'This is not legal advice' },
  body: {
    es: 'Responda con la verdad: una respuesta falsa puede impedir su residencia para siempre. Si alguna respuesta es Sí, o no está seguro/a, hable con un abogado de inmigración o un representante acreditado (DOJ) antes de presentar el formulario.',
    en: 'Answer truthfully: a false answer can bar your residence permanently. If any answer is Yes, or you’re not sure, talk to an immigration attorney or a DOJ-accredited representative before you file.',
  },
};

/** Part 2, Item 3: the categories the app offers, with their PDF box. Others go in "Other Eligibility". */
export const CATEGORIES: (Option & { box: string })[] = [
  { value: 'ir-spouse', box: '3a0', label: { es: 'Cónyuge de un ciudadano de EE.UU.', en: 'Spouse of a U.S. citizen' } },
  { value: 'ir-child', box: '3a1', label: { es: 'Hijo/a soltero/a menor de 21 años de un ciudadano', en: 'Unmarried child under 21 of a U.S. citizen' } },
  { value: 'ir-parent', box: '3a2', label: { es: 'Padre o madre de un ciudadano (de 21 años o más)', en: 'Parent of a U.S. citizen (at least 21)' } },
  { value: 'k1', box: '3a3', label: { es: 'Prometido/a (K-1) o hijo/a de prometido/a (K-2) de un ciudadano', en: 'K-1 fiancé(e) or K-2 child of a fiancé(e) of a U.S. citizen' } },
  { value: 'widow', box: '3a4', label: { es: 'Viudo/a de un ciudadano', en: 'Widow or widower of a U.S. citizen' } },
  { value: 'ndaa', box: '3a5', label: { es: 'Cónyuge, hijo/a o padre/madre de un militar fallecido en servicio activo (NDAA)', en: 'Spouse, child, or parent of a deceased active-duty service member (NDAA)' } },
  { value: 'f1', box: '3a6', label: { es: 'Hijo/a soltero/a de 21 años o más de un ciudadano', en: 'Unmarried son or daughter (21 or older) of a U.S. citizen' } },
  { value: 'f3', box: '3a7', label: { es: 'Hijo/a casado/a de un ciudadano', en: 'Married son or daughter of a U.S. citizen' } },
  { value: 'f4', box: '3a8', label: { es: 'Hermano/a de un ciudadano (de 21 años o más)', en: 'Brother or sister of a U.S. citizen (at least 21)' } },
  { value: 'f2a-spouse', box: '3a9', label: { es: 'Cónyuge de un residente permanente', en: 'Spouse of a permanent resident' } },
  { value: 'f2a-child', box: '3a10', label: { es: 'Hijo/a soltero/a menor de 21 años de un residente', en: 'Unmarried child under 21 of a permanent resident' } },
  { value: 'f2b', box: '3a11', label: { es: 'Hijo/a soltero/a de 21 años o más de un residente', en: 'Unmarried son or daughter (21 or older) of a permanent resident' } },
  { value: 'vawa-spouse', box: '3a12', label: { es: 'VAWA: cónyuge autopeticionario/a', en: 'VAWA self-petitioning spouse' } },
  { value: 'vawa-child', box: '3a13', label: { es: 'VAWA: hijo/a autopeticionario/a', en: 'VAWA self-petitioning child' } },
  { value: 'vawa-parent', box: '3a14', label: { es: 'VAWA: padre o madre autopeticionario/a', en: 'VAWA self-petitioning parent' } },
  { value: 'asylee', box: '3d0', label: { es: 'Asilado/a (me otorgaron asilo hace al menos un año)', en: 'Asylee (granted asylum at least a year ago)' } },
  { value: 'refugee', box: '3d1', label: { es: 'Refugiado/a', en: 'Refugee' } },
  { value: 'cuban', box: '3f0', label: { es: 'Ley de Ajuste Cubano', en: 'Cuban Adjustment Act' } },
  { value: 'dv', box: '3g0', label: { es: 'Lotería de visas (Diversity Visa)', en: 'Diversity Visa program' } },
  { value: 'other', box: '3g4', label: { es: 'Otra categoría (empleo, inmigrante especial, T/U…)', en: 'Another category (employment, special immigrant, T/U…)' } },
];

/** Public charge exemptions, Part 9 Item 56, in printed order, with each box's export value. */
export const PUBLIC_CHARGE_EXEMPTIONS: { value: string; es: string; en: string }[] = [
  { value: '5', es: 'VAWA (I-360)', en: 'VAWA Self-Petitioner (Form I-360)' },
  { value: '6', es: 'Menor inmigrante especial (SIJ)', en: 'Special Immigrant Juvenile' },
  { value: '0', es: 'Ciertos afganos o iraquíes', en: 'Certain Afghan or Iraqi National' },
  { value: '3', es: 'Asilado/a', en: 'Asylee' },
  { value: '1', es: 'Refugiado/a', en: 'Refugee' },
  { value: '2', es: 'Víctima de delito (visa U) bajo INA 245(m)', en: 'U nonimmigrant under INA 245(m)' },
  { value: '4', es: 'Otra categoría, con visa U válida', en: 'Any other category, in valid U status' },
  { value: '9', es: 'Víctima de trata (visa T) bajo INA 245(l)', en: 'T nonimmigrant under INA 245(l)' },
  { value: '12', es: 'Otra categoría, con visa T pendiente o válida', en: 'Any other category, with pending or valid T status' },
  { value: '7', es: 'Ley de Ajuste Cubano', en: 'Cuban Adjustment Act' },
  { value: '10', es: 'Ajuste Cubano para cónyuges e hijos maltratados', en: 'Cuban Adjustment Act for Battered Spouses and Children' },
  { value: '11', es: 'Dependiente bajo la ley HRIFA (haitianos)', en: 'Dependent under HRIFA' },
  { value: '8', es: 'HRIFA para cónyuges e hijos maltratados', en: 'HRIFA for Battered Spouses and Children' },
  { value: '17', es: 'Entrantes cubanos y haitianos (IRCA sección 202)', en: 'Cuban and Haitian Entrants (IRCA section 202)' },
  { value: '18', es: 'Parolee Lautenberg', en: 'Lautenberg Parolee' },
  { value: '19', es: 'Nacionales de Vietnam, Camboya o Laos', en: 'National of Vietnam, Cambodia, or Laos' },
  { value: '13', es: 'Residencia continua desde antes de 1972 (Registry)', en: 'Registry (since before January 1, 1972)' },
  { value: '15', es: 'Ley de Regreso Amerasiático', en: 'Amerasian Homecoming Act' },
  { value: '16', es: 'Parolee polaco o húngaro', en: 'Polish or Hungarian Parolee' },
  { value: '14', es: 'NACARA (nicaragüenses y centroamericanos)', en: 'NACARA' },
  { value: '20', es: 'Indígena americano nacido en Canadá o Kickapoo de Texas', en: 'American Indian Born in Canada or Texas Band of Kickapoo' },
  { value: '21', es: 'Refugiados liberianos (NDAA 2020, sección 7611)', en: 'Liberian Refugee Immigration Fairness' },
  { value: '24', es: 'Sirios bajo la ley 106-378', en: 'Syrian National under Public Law 106-378' },
  { value: '22', es: 'Familiar de un militar en servicio activo (NDAA)', en: 'Spouse, Child, or Parent of an Active-Duty Service Member (NDAA)' },
];

const NOT_EXEMPT = '23';
const notExempt = is('publicCharge.exemption', NOT_EXEMPT);

const ranges = (id: string, ref: string, es: string, en: string, labels: string[]): Question => ({
  id,
  kind: 'choice',
  formRef: ref,
  showIf: notExempt,
  question: { es, en },
  options: labels.map((l, i) => ({ value: 'ABCDE'[i], label: { es: l, en: l } })),
});

const explainPage = (item: string) => P9_ITEMS.find((it) => it.item === item)!.page;

const nameAtBirth = (prefix: string, ref: string): Field[] =>
  nameFields(prefix, ref, false).map((f) => ({ ...f, label: { es: `${f.label.es} al nacer (si era otro)`, en: `${f.label.en} at birth (if different)` } }));

const t = (es: string, en: string): T => ({ es, en });

export const i485: FormDefinition = {
  id: 'i-485',
  number: 'I-485',
  edition: I485_EDITION,
  title: { es: 'Solicitud de residencia permanente (ajuste de estatus)', en: 'Application to Register Permanent Residence or Adjust Status' },
  summary: {
    es: 'Pida la green card desde dentro de EE.UU. si ya tiene una petición (I-130 u otra) o una categoría que lo permita.',
    en: 'Apply for a green card from inside the U.S. if you have a petition (I-130 or other) or a category that allows it.',
  },
  intro: {
    es: 'Con el I-485 usted pide a USCIS la residencia permanente (green card) sin salir de EE.UU. Le preguntaremos sobre usted, su entrada a EE.UU., su categoría, su familia y su historial. Es un formulario largo: puede guardar y seguir después.',
    en: 'With Form I-485 you ask USCIS for permanent residence (a green card) without leaving the U.S. We’ll ask about you, your entry, your category, your family and your history. It’s a long form: you can save and continue later.',
  },
  minutes: 75,
  pdf: {
    path: 'forms/i-485.pdf',
    fileName: 'I-485-filled.pdf',
    load: () => import('../pdf/i485Pdf').then((m) => m.fillI485),
    signHere: { es: 'Parte 10, Ítem 4', en: 'Part 10, Item 4' },
  },
  nextSteps: {
    es: [
      'Confirme en uscis.gov/i-485 que la edición {edition} sigue vigente; si cambió, use la nueva y copie sus respuestas de esta hoja.',
      'Revise el PDF página por página. Lo que no cupo (más direcciones, organizaciones, hijos, beneficios o explicaciones) va a mano en la Parte 14.',
      'Revise la tarifa actual en uscis.gov/g-1055 y las pruebas que pide su categoría: acta de nacimiento, fotos, examen médico (I-693) y, en la mayoría de los casos familiares, la declaración de patrocinio (I-864).',
      'Imprima el PDF y firme la Parte 10, Ítem 4, a mano con tinta negra. No llene la Parte 13: se firma en la entrevista.',
    ],
    en: [
      'Check at uscis.gov/i-485 that edition {edition} is still current; if it changed, use the new one and copy your answers from this sheet.',
      'Check the PDF page by page. Anything that didn’t fit (more addresses, organizations, children, benefits or explanations) goes by hand in Part 14.',
      'Check the current fee at uscis.gov/g-1055 and the evidence your category needs: birth certificate, photos, medical exam (I-693) and, in most family cases, the affidavit of support (I-864).',
      'Print the PDF and sign Part 10, Item 4, by hand in black ink. Leave Part 13 blank: it is signed at the interview.',
    ],
  },
  sections: [
    {
      id: 'about',
      part: 'Part 1',
      title: t('Sobre usted', 'About you'),
      questions: [
        {
          id: 'name',
          kind: 'fields',
          formRef: 'Part 1 · Item 1 · Your Current Legal Name',
          question: t('¿Cuál es su nombre legal actual?', 'What is your current legal name?'),
          why: t('No use apodos. Use letras latinas; los acentos se quitan al llenar el PDF.', 'Don’t use a nickname. Use Latin letters; accents are removed when the PDF is filled.'),
          fields: nameFields('name', 'Part 1 · Item 1'),
        },
        {
          id: 'hasOtherNames',
          kind: 'choice',
          formRef: 'Part 1 · Item 2 · Other Names You Have Used Since Birth',
          question: t('¿Ha usado otros nombres desde que nació?', 'Have you used other names since birth?'),
          why: t('Incluya su nombre al nacer si era otro, apellidos de casada, apodos y alias.', 'Include your birth name if different, married names, nicknames and aliases.'),
          options: yesNo,
        },
        {
          id: 'otherName1',
          kind: 'fields',
          formRef: 'Part 1 · Item 2 (row 1)',
          showIf: is('hasOtherNames', 'yes'),
          question: t('¿Qué otro nombre ha usado?', 'What other name have you used?'),
          fields: nameFields('otherName1', 'Part 1 · Item 2 (row 1)'),
        },
        {
          id: 'hasOtherNames2',
          kind: 'choice',
          formRef: 'Part 1 · Item 2',
          showIf: is('hasOtherNames', 'yes'),
          question: t('¿Ha usado otro nombre más?', 'Have you used another name?'),
          options: yesNo,
        },
        {
          id: 'otherName2',
          kind: 'fields',
          formRef: 'Part 1 · Item 2 (row 2)',
          showIf: all(is('hasOtherNames', 'yes'), is('hasOtherNames2', 'yes')),
          question: t('¿Qué otro nombre ha usado?', 'What other name have you used?'),
          why: t('Si usó más, escríbalos a mano en la Parte 14.', 'If you used more, write them by hand in Part 14.'),
          fields: nameFields('otherName2', 'Part 1 · Item 2 (row 2)'),
        },
        {
          id: 'birth',
          kind: 'fields',
          formRef: 'Part 1 · Items 3, 6–8',
          question: t('¿Cuándo y dónde nació?', 'When and where were you born?'),
          fields: [
            date('dob', 'Fecha de nacimiento', 'Date of birth', 'Part 1 · Item 3 · Date of Birth'),
            sexField('sex', 'Part 1 · Item 6'),
            { id: 'birthCity', type: 'text', required: true, label: { es: 'Ciudad de nacimiento', en: 'City of birth' }, formRef: 'Part 1 · Item 7 · City or Town of Birth' },
            { id: 'birthCountry', type: 'text', required: true, label: { es: 'País de nacimiento', en: 'Country of birth' }, formRef: 'Part 1 · Item 7 · Country of Birth' },
            { id: 'citizenship', type: 'text', required: true, label: { es: 'País de ciudadanía', en: 'Country of citizenship' }, formRef: 'Part 1 · Item 8 · Country of Citizenship or Nationality' },
          ],
        },
        {
          id: 'otherDob',
          kind: 'choice',
          formRef: 'Part 1 · Item 3 · Have you ever used any other date of birth?',
          question: t('¿Alguna vez ha usado otra fecha de nacimiento?', 'Have you ever used another date of birth?'),
          options: yesNo,
        },
        {
          id: 'otherDobs',
          kind: 'fields',
          formRef: 'Part 1 · Item 3 · Other dates of birth',
          showIf: is('otherDob', 'yes'),
          question: t('¿Qué otras fechas de nacimiento ha usado?', 'What other dates of birth have you used?'),
          fields: [date('otherDob1', 'Otra fecha', 'Other date', 'Part 1 · Item 3 (1)'), date('otherDob2', 'Otra fecha más', 'Another date', 'Part 1 · Item 3 (2)', false)],
        },
        {
          id: 'ids',
          kind: 'fields',
          formRef: 'Part 1 · Items 4–5, 9',
          question: t('Sus números de inmigración', 'Your immigration numbers'),
          why: t('Deje vacíos los que no tenga. El A-Number aparece en cartas de USCIS o en un permiso de trabajo.', 'Leave empty the ones you don’t have. The A-Number is on USCIS letters or a work permit.'),
          fields: [
            { id: 'aNumber', type: 'aNumber', label: { es: 'A-Number', en: 'A-Number' }, formRef: 'Part 1 · Item 4 · Alien Registration Number', placeholder: 'A123456789' },
            { id: 'otherA1', type: 'aNumber', label: { es: 'Otro A-Number que le hayan dado', en: 'Any other A-Number assigned to you' }, formRef: 'Part 1 · Item 5 · Other A-Numbers' },
            { id: 'otherA2', type: 'aNumber', label: { es: 'Otro A-Number más', en: 'Another A-Number' }, formRef: 'Part 1 · Item 5 · Other A-Numbers' },
            { id: 'uscisAccount', type: 'uscisAccount', label: { es: 'Número de cuenta en línea de USCIS', en: 'USCIS online account number' }, formRef: 'Part 1 · Item 9 · USCIS Online Account Number' },
          ],
        },
      ],
    },
    {
      id: 'arrival',
      part: 'Part 1',
      title: t('Su entrada a EE.UU.', 'Your entry to the U.S.'),
      questions: [
        {
          id: 'arrivalHow',
          kind: 'choice',
          formRef: 'Part 1 · Item 11 · When I last arrived in the United States',
          question: t('¿Cómo entró a EE.UU. la última vez?', 'How did you last enter the U.S.?'),
          notice: {
            tone: 'legal',
            title: { es: 'Su forma de entrada importa', en: 'How you entered matters' },
            body: {
              es: 'En muchos casos, quien entró sin inspección no puede ajustar su estatus dentro de EE.UU. (salvo excepciones como la sección 245(i)). Si es su caso, hable con un abogado o representante acreditado antes de presentar.',
              en: 'In many cases, people who entered without inspection can’t adjust status inside the U.S. (with exceptions such as section 245(i)). If that’s your case, talk to an attorney or accredited representative before filing.',
            },
          },
          options: [
            { value: 'admitted', label: t('Me inspeccionaron y me admitieron (con visa, por ejemplo B-2, F-1, K-1)', 'I was inspected and admitted (with a visa, for example B-2, F-1, K-1)') },
            { value: 'paroled', label: t('Me inspeccionaron y me dieron parole', 'I was inspected and paroled') },
            { value: 'ewi', label: t('Entré sin admisión ni parole', 'I came in without admission or parole') },
            { value: 'other', label: t('Otra forma', 'Other') },
          ],
        },
        {
          id: 'arrivalAs',
          kind: 'fields',
          formRef: 'Part 1 · Item 11',
          showIf: is('arrivalHow', 'admitted', 'paroled', 'other'),
          question: t('¿Como qué entró?', 'What did you enter as?'),
          fields: [
            { id: 'arrivalAs.text', type: 'text', required: true, label: { es: 'Admitido/a o con parole como (por ejemplo: visitor B-2, student F-1, humanitarian parole)', en: 'Admitted or paroled as' }, formRef: 'Part 1 · Item 11 · Admitted / Paroled as / Other', placeholder: 'B-2 visitor' },
          ],
        },
        {
          id: 'lastArrival',
          kind: 'fields',
          formRef: 'Part 1 · Item 10 · Recent Immigration History',
          question: t('Sobre su última llegada', 'About your last arrival'),
          why: t('Si entró con pasaporte o documento de viaje, escriba sus datos. Deje vacío lo que no aplique.', 'If you entered with a passport or travel document, give its details. Leave empty what doesn’t apply.'),
          fields: [
            { id: 'arrival.city', type: 'text', required: true, label: { es: 'Ciudad de llegada', en: 'City of arrival' }, formRef: 'Part 1 · Item 10 · Place of Last Arrival: City or Town' },
            { id: 'arrival.state', type: 'state', required: true, label: { es: 'Estado de llegada', en: 'State of arrival' }, formRef: 'Part 1 · Item 10 · State' },
            date('arrival.date', 'Fecha de la última llegada', 'Date of last arrival', 'Part 1 · Item 10 · Date of Last Arrival'),
            { id: 'passport.number', type: 'text', label: { es: 'Número de pasaporte o documento de viaje', en: 'Passport or travel document number' }, formRef: 'Part 1 · Item 10 · Passport or Travel Document Number Used at Last Arrival' },
            date('passport.expires', 'Vencimiento del pasaporte', 'Passport expiration', 'Part 1 · Item 10 · Expiration Date', false, 'date'),
            { id: 'passport.country', type: 'text', label: { es: 'País que lo emitió', en: 'Country that issued it' }, formRef: 'Part 1 · Item 10 · Country that Issued this Passport or Travel Document' },
            { id: 'visa.number', type: 'text', label: { es: 'Número de visa de no inmigrante', en: 'Nonimmigrant visa number' }, formRef: 'Part 1 · Item 10 · Nonimmigrant Visa Number' },
            date('visa.issued', 'Fecha en que se emitió la visa', 'Date the visa was issued', 'Part 1 · Item 10 · Date Nonimmigrant Visa Was Issued', false),
          ],
        },
        {
          id: 'i94',
          kind: 'fields',
          formRef: 'Part 1 · Item 12 · Form I-94 Arrival/Departure Record',
          showIf: (a) => a.arrivalHow !== 'ewi',
          question: t('Datos de su I-94 más reciente', 'Details from your most recent I-94'),
          why: t('Lo puede bajar en i94.cbp.dhs.gov. Si no tiene I-94, deje los campos vacíos.', 'You can download it at i94.cbp.dhs.gov. If you don’t have one, leave the fields empty.'),
          fields: [
            { id: 'i94.family', type: 'text', label: { es: 'Apellido como aparece en el I-94', en: 'Family name as on the I-94' }, formRef: 'Part 1 · Item 12 · Family Name' },
            { id: 'i94.given', type: 'text', label: { es: 'Nombre como aparece en el I-94', en: 'Given name as on the I-94' }, formRef: 'Part 1 · Item 12 · Given Name' },
            { id: 'i94.number', type: 'i94', label: { es: 'Número I-94', en: 'I-94 number' }, formRef: 'Part 1 · Item 12 · Form I-94 Arrival-Departure Record Number' },
            { id: 'i94.expires', type: 'text', label: { es: 'Vencimiento de la estadía (fecha o "D/S")', en: 'Authorized stay expires (date or "D/S")' }, formRef: 'Part 1 · Item 12 · Expiration Date of Authorized Stay', placeholder: 'MM/DD/AAAA' },
            { id: 'i94.status', type: 'text', label: { es: 'Estatus en el I-94 (por ejemplo B2)', en: 'Status on the I-94 (for example B2)' }, formRef: 'Part 1 · Item 12 · Immigration Status on Form I-94', maxLength: 20 },
          ],
        },
        {
          id: 'statusNow',
          kind: 'fields',
          formRef: 'Part 1 · Items 14–15',
          question: t('¿Cuál es su estatus migratorio actual?', 'What is your current immigration status?'),
          why: t('Por ejemplo: B-2, F-1, parolee, TPS, "no status". Si no cambió desde su llegada, repita el mismo.', 'For example: B-2, F-1, parolee, TPS, "no status". If it hasn’t changed since you arrived, repeat it.'),
          fields: [
            { id: 'status.current', type: 'text', required: true, label: { es: 'Estatus actual', en: 'Current status' }, formRef: 'Part 1 · Item 14 · Current Immigration Status', maxLength: 20 },
            { id: 'status.expires', type: 'text', label: { es: 'Vencimiento (fecha o "D/S")', en: 'Expiration (date or "D/S")' }, formRef: 'Part 1 · Item 15 · Expiration Date of Current Immigration Status' },
          ],
        },
        {
          id: 'arrivalYN',
          kind: 'yesNoList',
          formRef: 'Part 1 · Items 13, 16–17',
          question: t('Un poco más sobre su llegada', 'A bit more about your arrival'),
          items: [
            { id: 'firstTime', label: t('¿Su última llegada fue la primera vez que estuvo en EE.UU.?', 'Was your last arrival the first time you were in the U.S.?'), formRef: 'Part 1 · Item 13' },
            { id: 'crewmanVisa', label: t('¿Alguna vez le dieron una visa de tripulante (crewman)?', 'Have you ever been issued an alien crewman visa?'), formRef: 'Part 1 · Item 16' },
            { id: 'crewmanArrival', label: t('¿Llegó para trabajar en un barco o avión como tripulante?', 'Did you last arrive to join a vessel or aircraft as crew?'), formRef: 'Part 1 · Item 17' },
          ],
        },
      ],
    },
    {
      id: 'addresses',
      part: 'Part 1',
      title: t('Sus direcciones', 'Your addresses'),
      questions: [
        {
          id: 'home',
          kind: 'fields',
          formRef: 'Part 1 · Item 18 · Current U.S. Physical Address',
          question: t('¿Dónde vive en EE.UU.?', 'Where do you live in the U.S.?'),
          fields: [...usAddress('home', 'Part 1 · Item 18', true), date('home.from', 'Vive aquí desde', 'Living here since', 'Part 1 · Item 18 · Date You First Resided at This Address')],
        },
        {
          id: 'mailingSame',
          kind: 'choice',
          formRef: 'Part 1 · Item 18 · Is this your current mailing address?',
          question: t('¿Recibe su correo en esa dirección?', 'Do you get your mail at that address?'),
          options: yesNo,
        },
        {
          id: 'mailing',
          kind: 'fields',
          formRef: 'Part 1 · Item 18 · Current Mailing Address',
          showIf: is('mailingSame', 'no'),
          question: t('¿A qué dirección le llega el correo?', 'Where do you get your mail?'),
          fields: usAddress('mailing', 'Part 1 · Item 18 · Mailing', true),
        },
        {
          id: 'fiveYears',
          kind: 'choice',
          formRef: 'Part 1 · Item 18 · Have you resided at your current address for at least 5 years?',
          question: t('¿Ha vivido en su dirección actual por al menos 5 años?', 'Have you lived at your current address for at least 5 years?'),
          options: yesNo,
        },
        {
          id: 'prior',
          kind: 'fields',
          formRef: 'Part 1 · Item 18 · Prior Address',
          showIf: is('fiveYears', 'no'),
          question: t('¿Dónde vivía antes?', 'Where did you live before?'),
          why: t('Si vivió en más lugares en los últimos 5 años, escríbalos a mano en la Parte 14.', 'If you lived in more places in the last 5 years, write them by hand in Part 14.'),
          fields: [...anyAddress('prior', 'Part 1 · Item 18 · Prior Address', { careOf: true }), date('prior.from', 'Desde', 'From', 'Part 1 · Item 18 · Dates of Residence From'), date('prior.to', 'Hasta', 'To', 'Part 1 · Item 18 · Dates of Residence To')],
        },
        {
          id: 'abroad',
          kind: 'fields',
          formRef: 'Part 1 · Item 18 · Most Recent Address Outside the United States',
          question: t('¿Cuál fue su última dirección fuera de EE.UU. donde vivió más de un año?', 'What was your most recent address outside the U.S. where you lived more than a year?'),
          why: t('Si ya la escribió arriba o nunca vivió fuera, deje los campos vacíos.', 'If you already listed it or never lived abroad, leave the fields empty.'),
          fields: [
            ...anyAddress('abroad', 'Part 1 · Item 18 · Outside the U.S.').map((f) => ({ ...f, required: false })),
            date('abroad.from', 'Desde', 'From', 'Part 1 · Item 18 · From', false),
            date('abroad.to', 'Hasta', 'To', 'Part 1 · Item 18 · To', false),
          ],
        },
      ],
    },
    {
      id: 'ssa',
      part: 'Part 1',
      title: t('Seguro Social', 'Social Security'),
      questions: [
        {
          id: 'ssaIssued',
          kind: 'choice',
          formRef: 'Part 1 · Item 19 · Has the SSA ever officially issued a Social Security card to you?',
          question: t('¿El Seguro Social le ha dado alguna vez una tarjeta?', 'Has Social Security ever issued you a card?'),
          options: yesNo,
        },
        {
          id: 'ssnQ',
          kind: 'fields',
          formRef: 'Part 1 · Item 19 · U.S. Social Security Number',
          showIf: is('ssaIssued', 'yes'),
          question: t('¿Cuál es su número de Seguro Social?', 'What is your Social Security number?'),
          fields: [{ id: 'ssn', type: 'ssn', required: true, label: { es: 'Número de Seguro Social', en: 'Social Security number' }, formRef: 'Part 1 · Item 19 · SSN', placeholder: '123-45-6789' }],
        },
        {
          id: 'ssaWants',
          kind: 'choice',
          formRef: 'Part 1 · Item 19 · Do you want the SSA to issue you a Social Security card?',
          question: t('¿Quiere que el Seguro Social le envíe una tarjeta?', 'Do you want Social Security to issue you a card?'),
          options: yesNo,
        },
        {
          id: 'ssaConsent',
          kind: 'choice',
          formRef: 'Part 1 · Item 19 · Consent for Disclosure',
          showIf: is('ssaWants', 'yes'),
          question: t('¿Permite que USCIS comparta sus datos con el Seguro Social para hacer la tarjeta?', 'Do you allow USCIS to share your information with Social Security to make the card?'),
          why: t('Debe responder Sí para recibir la tarjeta.', 'You must answer Yes to receive the card.'),
          options: yesNo,
        },
      ],
    },
    {
      id: 'category',
      part: 'Part 2',
      title: t('Su categoría', 'Your category'),
      questions: [
        {
          id: 'category',
          kind: 'choice',
          formRef: 'Part 2 · Item 3 · I am applying based on the following category',
          question: t('¿En qué categoría pide la residencia?', 'Which category are you applying under?'),
          why: t('Elija solo una. Si es derivado/a (cónyuge o hijo/a del solicitante principal), elija la categoría del principal.', 'Choose only one. If you’re a derivative (spouse or child of the principal), choose the principal’s category.'),
          options: CATEGORIES,
        },
        {
          id: 'asylumDateQ',
          kind: 'fields',
          formRef: 'Part 2 · Item 3.d · Asylum Status',
          showIf: is('category', 'asylee'),
          question: t('¿Cuándo le otorgaron el asilo?', 'When were you granted asylum?'),
          fields: [date('category.asylumDate', 'Fecha', 'Date', 'Part 2 · Item 3.d · Date you were granted asylum')],
        },
        {
          id: 'refugeeDateQ',
          kind: 'fields',
          formRef: 'Part 2 · Item 3.d · Refugee Status',
          showIf: is('category', 'refugee'),
          question: t('¿Cuándo lo/la admitieron como refugiado/a?', 'When were you admitted as a refugee?'),
          fields: [date('category.refugeeDate', 'Fecha de la primera admisión', 'Date of initial admission', 'Part 2 · Item 3.d · Date of initial admission as refugee')],
        },
        {
          id: 'dvRankQ',
          kind: 'fields',
          formRef: 'Part 2 · Item 3.g · Diversity Visa program',
          showIf: is('category', 'dv'),
          question: t('¿Cuál es su número de rango de la lotería?', 'What is your Diversity Visa rank number?'),
          fields: [{ id: 'category.dvRank', type: 'text', required: true, label: { es: 'Número de rango', en: 'Rank number' }, formRef: 'Part 2 · Item 3.g · Diversity Visa Rank Number' }],
        },
        {
          id: 'otherCategoryQ',
          kind: 'fields',
          formRef: 'Part 2 · Item 3.g · Other Eligibility',
          showIf: is('category', 'other'),
          question: t('¿Cuál es su categoría?', 'What is your category?'),
          why: t('Escríbala en inglés como aparece en las instrucciones del I-485 (por ejemplo: "EB-2, Form I-140"). Si es de empleo o especial, conviene consultar a un abogado.', 'Write it as it appears in the I-485 instructions (for example: "EB-2, Form I-140").'),
          fields: [{ id: 'category.other', type: 'text', required: true, label: { es: 'Categoría', en: 'Category' }, formRef: 'Part 2 · Item 3.g · Other Eligibility' }],
        },
        {
          id: 'underlying',
          kind: 'fields',
          formRef: 'Part 2 · Item 2 · Underlying Petition',
          question: t('¿Tiene el recibo de la petición (I-130 u otra)?', 'Do you have the receipt for the petition (I-130 or other)?'),
          why: t('Aparece en el aviso I-797. Si presenta todo junto, déjelo vacío.', 'It’s on the I-797 notice. If you’re filing everything together, leave it empty.'),
          fields: [
            { id: 'petition.receipt', type: 'receipt', label: { es: 'Número de recibo', en: 'Receipt number' }, formRef: 'Part 2 · Item 2 · Receipt Number of Underlying Petition', placeholder: 'IOE0123456789' },
            date('petition.priority', 'Fecha de prioridad', 'Priority date', 'Part 2 · Item 2 · Priority Date', false),
          ],
        },
        {
          id: 'applicantType',
          kind: 'choice',
          formRef: 'Part 2 · Item 2 · I am filing this Form I-485 as a',
          question: t('¿Usted es el solicitante principal o un derivado?', 'Are you the principal applicant or a derivative?'),
          why: t('Derivado es el cónyuge o hijo/a de la persona que tiene la categoría (por ejemplo, la familia de un ganador de la lotería).', 'A derivative is the spouse or child of the person who has the category (for example, the family of a lottery winner).'),
          options: [
            { value: 'principal', label: t('Solicitante principal', 'Principal applicant') },
            { value: 'derivative', label: t('Derivado/a', 'Derivative applicant') },
          ],
        },
        {
          id: 'principal',
          kind: 'fields',
          formRef: 'Part 2 · Item 2 · Principal Applicant',
          showIf: is('applicantType', 'derivative'),
          question: t('¿Quién es el solicitante principal?', 'Who is the principal applicant?'),
          fields: [
            ...nameFields('principal', 'Part 2 · Principal Applicant’s Name'),
            { id: 'principal.aNumber', type: 'aNumber', label: { es: 'A-Number del principal', en: 'Principal’s A-Number' }, formRef: 'Part 2 · Principal Applicant’s A-Number' },
            date('principal.dob', 'Fecha de nacimiento del principal', 'Principal’s date of birth', 'Part 2 · Principal Applicant’s Date of Birth'),
          ],
        },
        {
          id: 'categoryYN',
          kind: 'yesNoList',
          formRef: 'Part 2 · Items 1, 4–5',
          question: t('Preguntas sobre su solicitud', 'Questions about your application'),
          items: [
            { id: 'eoir', label: t('¿Presenta este ajuste ante la corte de inmigración (EOIR) porque está en un proceso de remoción?', 'Are you filing with the immigration court (EOIR) while in removal proceedings?'), formRef: 'Part 2 · Item 1' },
            { id: 'section245i', label: t('¿Pide el ajuste basado en la sección 245(i)?', 'Are you applying for adjustment based on INA section 245(i)?'), formRef: 'Part 2 · Item 4', showIf: (a) => a.category !== 'asylee' && a.category !== 'refugee' },
            { id: 'cspa', label: t('¿Tiene 21 años o más y pide como hijo/a bajo la Ley de Protección del Estatus del Menor (CSPA)?', 'Are you 21 or older and applying as a child under the Child Status Protection Act (CSPA)?'), formRef: 'Part 2 · Item 5' },
          ],
        },
        {
          id: 'affidavitExemption',
          kind: 'choice',
          formRef: 'Part 3 · Item 1 · Request for Exemption for Intending Immigrant’s Affidavit of Support',
          question: t('¿Necesita presentar una declaración de patrocinio (I-864)?', 'Do you need to submit an affidavit of support (I-864)?'),
          why: t('La mayoría de los casos familiares la necesitan. Las exenciones son pocas.', 'Most family cases need one. Exemptions are few.'),
          options: [
            { value: '5', label: t('Sí, presento el I-864 (no pido exención)', 'Yes, I submit Form I-864 (no exemption)') },
            { value: '4', label: t('No aplica: mi categoría no lo requiere', 'Not required: my category doesn’t require it') },
            { value: '0', label: t('Exención: tengo (o puedo sumar) 40 trimestres de trabajo en EE.UU.', 'Exemption: I have (or can be credited with) 40 quarters of U.S. work') },
            { value: '1', label: t('Exención: soy menor de 18, soltero/a, hijo/a de ciudadano y seré ciudadano/a automáticamente', 'Exemption: I’m under 18, unmarried, a citizen’s child and will automatically become a citizen') },
            { value: '2', label: t('Exención: soy viudo/a de ciudadano (I-360)', 'Exemption: I’m a widow(er) of a U.S. citizen (I-360)') },
            { value: '3', label: t('Exención: soy autopeticionario/a VAWA', 'Exemption: I’m a VAWA self-petitioner') },
          ],
        },
      ],
    },
    {
      id: 'history',
      part: 'Part 4',
      title: t('Historial y trabajo', 'History and work'),
      questions: [
        {
          id: 'historyYN',
          kind: 'yesNoList',
          formRef: 'Part 4 · Items 1, 5–6',
          question: t('Solicitudes anteriores', 'Previous applications'),
          items: [
            { id: 'prevImmigrantVisa', label: t('¿Alguna vez ha pedido una visa de inmigrante en una embajada o consulado de EE.UU.?', 'Have you ever applied for an immigrant visa at a U.S. Embassy or Consulate?'), formRef: 'Part 4 · Item 1' },
            { id: 'prevLprInUS', label: t('¿Alguna vez ha pedido la residencia permanente estando en EE.UU.?', 'Have you previously applied for permanent residence while in the U.S.?'), formRef: 'Part 4 · Item 5' },
            { id: 'rescinded', label: t('¿Alguna vez tuvo la residencia y se la quitaron (rescindieron)?', 'Have you EVER held permanent resident status that was later rescinded?'), formRef: 'Part 4 · Item 6' },
          ],
        },
        {
          id: 'prevVisa',
          kind: 'fields',
          formRef: 'Part 4 · Items 2–4',
          showIf: is('prevImmigrantVisa', 'yes'),
          question: t('Sobre esa solicitud de visa', 'About that visa application'),
          fields: [
            { id: 'prevVisa.city', type: 'text', required: true, label: { es: 'Ciudad de la embajada o consulado', en: 'City of the embassy or consulate' }, formRef: 'Part 4 · Item 2 · City or Town' },
            { id: 'prevVisa.country', type: 'text', required: true, label: { es: 'País', en: 'Country' }, formRef: 'Part 4 · Item 2 · Country' },
            { id: 'prevVisa.decision', type: 'text', required: true, label: { es: 'Decisión (approved, refused, denied, withdrawn)', en: 'Decision' }, formRef: 'Part 4 · Item 3 · Decision' },
            date('prevVisa.date', 'Fecha de la decisión', 'Date of decision', 'Part 4 · Item 4 · Date of Decision', false),
          ],
        },
        {
          id: 'job',
          kind: 'fields',
          formRef: 'Part 4 · Item 7 · Employment and Educational History',
          question: t('¿Dónde trabaja o estudia ahora (o lo más reciente)?', 'Where do you work or study now (or most recently)?'),
          why: t('Si no trabaja o está jubilado/a, dígalo y explique de qué vive.', 'If you don’t work or are retired, say so and explain how you support yourself.'),
          fields: [
            {
              id: 'job.type',
              type: 'select',
              required: true,
              label: { es: 'Tipo', en: 'Type' },
              formRef: 'Part 4 · Item 7 · Employer or School (current or most recent)',
              options: [
                { value: 'Employer', label: t('Empleador', 'Employer') },
                { value: 'Self-employed', label: t('Trabajo por mi cuenta', 'Self-employed') },
                { value: 'School', label: t('Escuela', 'School') },
                { value: 'Unemployed', label: t('Sin empleo', 'Unemployed') },
                { value: 'Retired', label: t('Jubilado/a', 'Retired') },
              ],
            },
            { id: 'job.name', type: 'text', label: { es: 'Nombre del empleador o escuela', en: 'Name of employer or school' }, formRef: 'Part 4 · Item 7 · Name of Employer, Company, or School', maxLength: 34 },
            { id: 'job.occupation', type: 'text', required: true, label: { es: 'Su ocupación (o "unemployed" / "retired")', en: 'Your occupation' }, formRef: 'Part 4 · Item 7 · Your Occupation', maxLength: 34 },
            ...anyAddress('job', 'Part 4 · Item 7 · Address').map((f) => ({ ...f, required: false })),
            date('job.from', 'Desde', 'From', 'Part 4 · Item 7 · Dates From', false),
            { id: 'job.support', type: 'text', label: { es: 'Si no trabaja: ¿de qué vive?', en: 'If unemployed or retired: source of financial support' }, formRef: 'Part 4 · Item 7 · Source of financial support', maxLength: 34 },
          ],
        },
        {
          id: 'abroadJob.has',
          kind: 'choice',
          formRef: 'Part 4 · Item 8 · Most recent employer or school outside the United States',
          question: t('¿Trabajó o estudió fuera de EE.UU. (y no lo escribió arriba)?', 'Did you work or study outside the U.S. (not listed above)?'),
          options: yesNo,
        },
        {
          id: 'abroadJob',
          kind: 'fields',
          formRef: 'Part 4 · Item 8',
          showIf: is('abroadJob.has', 'yes'),
          question: t('Su trabajo o escuela más reciente fuera de EE.UU.', 'Your most recent job or school outside the U.S.'),
          fields: [
            { id: 'abroadJob.name', type: 'text', required: true, label: { es: 'Empleador o escuela', en: 'Employer or school' }, formRef: 'Part 4 · Item 8 · Name of Employer, Company, or School', maxLength: 34 },
            { id: 'abroadJob.occupation', type: 'text', label: { es: 'Su ocupación', en: 'Your occupation' }, formRef: 'Part 4 · Item 8 · Your Occupation', maxLength: 34 },
            ...anyAddress('abroadJob', 'Part 4 · Item 8 · Address').map((f) => ({ ...f, required: false })),
            date('abroadJob.from', 'Desde', 'From', 'Part 4 · Item 8 · From', false),
            date('abroadJob.to', 'Hasta', 'To', 'Part 4 · Item 8 · To', false),
          ],
        },
      ],
    },
    {
      id: 'parents',
      part: 'Part 5',
      title: t('Sus padres', 'Your parents'),
      questions: [1, 2].map(
        (p): Question => ({
          id: `parent${p}`,
          kind: 'fields',
          formRef: `Part 5 · Items ${p === 1 ? '1–4' : '5–8'} · Information About Your Parent ${p}`,
          question: p === 1 ? t('Sobre uno de sus padres', 'About one of your parents') : t('Sobre su otro padre o madre', 'About your other parent'),
          why: t('Si no sabe algún dato, escriba "unknown".', 'If you don’t know something, write "unknown".'),
          fields: [
            ...nameFields(`parent${p}`, `Part 5 · Parent ${p}’s Legal Name`),
            ...nameAtBirth(`parent${p}.birth`, `Part 5 · Parent ${p}’s Name at Birth`),
            date(`parent${p}.dob`, 'Fecha de nacimiento', 'Date of birth', `Part 5 · Parent ${p} · Date of Birth`, false),
            { id: `parent${p}.country`, type: 'text', label: { es: 'País de nacimiento', en: 'Country of birth' }, formRef: `Part 5 · Parent ${p} · Country of Birth` },
          ],
        }),
      ),
    },
    {
      id: 'marital',
      part: 'Part 6',
      title: t('Estado civil', 'Marital history'),
      questions: [
        {
          id: 'marital',
          kind: 'choice',
          formRef: 'Part 6 · Item 1 · Current Marital Status',
          question: t('¿Cuál es su estado civil?', 'What is your marital status?'),
          options: [
            { value: 'single', label: t('Soltero/a, nunca casado/a', 'Single, never married') },
            { value: 'married', label: t('Casado/a', 'Married') },
            { value: 'separated', label: t('Separado/a legalmente', 'Legally separated') },
            { value: 'divorced', label: t('Divorciado/a', 'Divorced') },
            { value: 'widowed', label: t('Viudo/a', 'Widowed') },
            { value: 'annulled', label: t('Matrimonio anulado', 'Marriage annulled') },
          ],
        },
        {
          id: 'timesMarriedQ',
          kind: 'fields',
          formRef: 'Part 6 · Item 3',
          showIf: (a) => !!a.marital && a.marital !== 'single',
          question: t('¿Cuántas veces se ha casado?', 'How many times have you been married?'),
          fields: [
            { id: 'timesMarried', type: 'number', required: true, label: { es: '¿Cuántas veces se ha casado? (incluya el actual y los anulados)', en: 'How many times have you been married?' }, formRef: 'Part 6 · Item 3', maxLength: 5 },
          ],
        },
        {
          id: 'spouseMilitary',
          kind: 'choice',
          formRef: 'Part 6 · Item 2 · Is your spouse a current member of the U.S. armed forces or U.S. Coast Guard?',
          showIf: is('marital', 'married', 'separated'),
          question: t('¿Su cónyuge está en las fuerzas armadas o la Guardia Costera de EE.UU.?', 'Is your spouse in the U.S. armed forces or Coast Guard?'),
          options: yesNo,
        },
        {
          id: 'spouse',
          kind: 'fields',
          formRef: 'Part 6 · Items 4–9 · Information About Your Current Marriage',
          showIf: is('marital', 'married', 'separated'),
          question: t('Sobre su cónyuge actual', 'About your current spouse'),
          fields: [
            ...nameFields('spouse', 'Part 6 · Item 4'),
            { id: 'spouse.aNumber', type: 'aNumber', label: { es: 'A-Number de su cónyuge', en: 'Spouse’s A-Number' }, formRef: 'Part 6 · Item 5' },
            date('spouse.dob', 'Fecha de nacimiento de su cónyuge', 'Spouse’s date of birth', 'Part 6 · Item 6'),
            { id: 'spouse.birthCountry', type: 'text', required: true, label: { es: 'País de nacimiento de su cónyuge', en: 'Spouse’s country of birth' }, formRef: 'Part 6 · Item 7' },
            date('spouse.married', 'Fecha de su matrimonio', 'Date of marriage', 'Part 6 · Item 9 · Date of Marriage to Current Spouse'),
            { id: 'spouse.marriedCity', type: 'text', required: true, label: { es: 'Ciudad donde se casaron', en: 'City of marriage' }, formRef: 'Part 6 · Item 9 · City or Town' },
            { id: 'spouse.marriedState', type: 'text', label: { es: 'Estado o provincia', en: 'State or province' }, formRef: 'Part 6 · Item 9 · State or Province' },
            { id: 'spouse.marriedCountry', type: 'text', required: true, label: { es: 'País', en: 'Country' }, formRef: 'Part 6 · Item 9 · Country' },
          ],
        },
        {
          id: 'spouseAddress',
          kind: 'fields',
          formRef: 'Part 6 · Item 8 · Current Spouse’s Current Physical Address',
          showIf: is('marital', 'married', 'separated'),
          question: t('¿Dónde vive su cónyuge?', 'Where does your spouse live?'),
          fields: anyAddress('spouse.home', 'Part 6 · Item 8'),
        },
        {
          id: 'spouseApplying',
          kind: 'choice',
          formRef: 'Part 6 · Item 10 · Is your current spouse applying with you?',
          showIf: is('marital', 'married', 'separated'),
          question: t('¿Su cónyuge también pide la residencia con usted?', 'Is your spouse applying with you?'),
          options: yesNo,
        },
        {
          id: 'priorSpouse',
          kind: 'fields',
          formRef: 'Part 6 · Items 11–18',
          showIf: (a) => num(a, 'timesMarried') > (is('marital', 'married', 'separated')(a) ? 1 : 0),
          question: t('Su cónyuge anterior', 'Your prior spouse'),
          fields: [
            ...nameFields('prior', 'Part 6 · Item 11 (family name before marriage)'),
            date('prior.dob', 'Fecha de nacimiento', 'Date of birth', 'Part 6 · Item 12', false),
            { id: 'prior.birthCountry', type: 'text', label: { es: 'País de nacimiento', en: 'Country of birth' }, formRef: 'Part 6 · Item 13' },
            { id: 'prior.citizenship', type: 'text', label: { es: 'País de ciudadanía', en: 'Country of citizenship' }, formRef: 'Part 6 · Item 14' },
            date('prior.married', 'Fecha del matrimonio', 'Date of marriage', 'Part 6 · Item 15'),
            { id: 'prior.marriedCity', type: 'text', label: { es: 'Ciudad donde se casaron', en: 'City of marriage' }, formRef: 'Part 6 · Item 16 · City or Town' },
            { id: 'prior.marriedState', type: 'text', label: { es: 'Estado o provincia', en: 'State or province' }, formRef: 'Part 6 · Item 16 · State or Province' },
            { id: 'prior.marriedCountry', type: 'text', label: { es: 'País', en: 'Country' }, formRef: 'Part 6 · Item 16 · Country' },
            { id: 'prior.endedCity', type: 'text', label: { es: 'Ciudad donde terminó el matrimonio', en: 'City where it ended' }, formRef: 'Part 6 · Item 17 · City or Town' },
            { id: 'prior.endedState', type: 'text', label: { es: 'Estado o provincia', en: 'State or province' }, formRef: 'Part 6 · Item 17 · State or Province' },
            { id: 'prior.endedCountry', type: 'text', label: { es: 'País', en: 'Country' }, formRef: 'Part 6 · Item 17 · Country' },
            date('prior.ended', 'Fecha en que terminó', 'Date it ended', 'Part 6 · Item 17 · Date Marriage Legally Ended'),
            {
              id: 'prior.how',
              type: 'select',
              required: true,
              label: { es: '¿Cómo terminó?', en: 'How did it end?' },
              formRef: 'Part 6 · Item 18',
              options: [
                { value: '2', label: t('Divorcio', 'Divorced') },
                { value: '3', label: t('Falleció mi cónyuge', 'Spouse deceased') },
                { value: '1', label: t('Anulación', 'Annulled') },
                { value: '4', label: t('Otra forma', 'Other') },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'children',
      part: 'Part 7',
      title: t('Hijos', 'Children'),
      questions: [
        {
          id: 'childrenQ',
          kind: 'fields',
          formRef: 'Part 7 · Item 1',
          question: t('¿Cuántos hijos vivos tiene en total?', 'How many living children do you have in total?'),
          why: t('Incluya hijos biológicos, adoptados e hijastros, de cualquier edad, en cualquier país, y los nacidos fuera del matrimonio. Si no tiene, escriba 0.', 'Include biological, adopted and stepchildren of any age, anywhere, and those born outside marriage. If none, enter 0.'),
          fields: [{ id: 'childrenCount', type: 'number', required: true, label: { es: 'Número de hijos', en: 'Number of children' }, formRef: 'Part 7 · Item 1', maxLength: 5, placeholder: '0' }],
        },
        ...[1, 2].map(
          (c): Question => ({
            id: `child${c}`,
            kind: 'fields',
            formRef: `Part 7 · Item ${c + 1} · Child ${c}`,
            showIf: (a) => num(a, 'childrenCount') >= c,
            question: t(`Su hijo/a número ${c}`, `Your child number ${c}`),
            why: c === 2 ? t('Si tiene más de 2, escriba los demás a mano en la Parte 14.', 'If you have more than 2, write the rest by hand in Part 14.') : undefined,
            fields: [
              ...nameFields(`child${c}`, `Part 7 · Child ${c}`),
              { id: `child${c}.aNumber`, type: 'aNumber', label: { es: 'A-Number', en: 'A-Number' }, formRef: `Part 7 · Child ${c} · A-Number` },
              date(`child${c}.dob`, 'Fecha de nacimiento', 'Date of birth', `Part 7 · Child ${c} · Date of Birth`),
              { id: `child${c}.country`, type: 'text', required: true, label: { es: 'País de nacimiento', en: 'Country of birth' }, formRef: `Part 7 · Child ${c} · Country of Birth` },
              { id: `child${c}.relationship`, type: 'text', required: true, label: { es: 'Relación (en inglés: biological child, stepchild, adopted child)', en: 'Relationship' }, formRef: `Part 7 · Child ${c} · Relationship`, maxLength: 34, placeholder: 'biological child' },
              { id: `child${c}.applying`, type: 'select', required: true, label: { es: '¿También pide ahora con su propio I-485?', en: 'Also applying now on a separate I-485?' }, formRef: `Part 7 · Child ${c}`, options: yesNo },
            ],
          }),
        ),
      ],
    },
    {
      id: 'biographic',
      part: 'Part 8',
      title: t('Datos biográficos', 'Biographic information'),
      questions: [
        {
          id: 'ethnicity',
          kind: 'choice',
          formRef: 'Part 8 · Item 1 · Ethnicity',
          question: t('¿Es usted hispano/a o latino/a?', 'Are you Hispanic or Latino?'),
          options: [
            { value: 'hispanic', label: t('Hispano/a o latino/a', 'Hispanic or Latino') },
            { value: 'notHispanic', label: t('No hispano/a ni latino/a', 'Not Hispanic or Latino') },
          ],
        },
        {
          id: 'race',
          kind: 'choice',
          multiple: true,
          formRef: 'Part 8 · Item 2 · Race',
          question: t('¿Cuál es su raza?', 'What is your race?'),
          why: t('Elija todas las que apliquen.', 'Choose all that apply.'),
          options: [
            { value: 'WH', label: t('Blanco/a', 'White') },
            { value: 'AS', label: t('Asiático/a', 'Asian') },
            { value: 'BL', label: t('Negro/a o afroamericano/a', 'Black or African American') },
            { value: 'AI', label: t('Indígena americano/a o nativo/a de Alaska', 'American Indian or Alaska Native') },
            { value: 'HW', label: t('Nativo/a de Hawái u otras islas del Pacífico', 'Native Hawaiian or Other Pacific Islander') },
          ],
        },
        {
          id: 'body',
          kind: 'fields',
          formRef: 'Part 8 · Items 3–6',
          question: t('Su estatura, peso y color de ojos y cabello', 'Your height, weight, and eye and hair color'),
          why: t('1.60 m son 5 pies 3 pulgadas; 70 kg son 154 libras.', 'In feet, inches and pounds.'),
          fields: [
            { id: 'heightFeet', type: 'select', required: true, label: { es: 'Estatura: pies', en: 'Height: feet' }, formRef: 'Part 8 · Item 3 · Feet', options: ['2', '3', '4', '5', '6', '7', '8'].map((v) => ({ value: v, label: { es: v, en: v } })) },
            { id: 'heightInches', type: 'select', required: true, label: { es: 'Estatura: pulgadas', en: 'Height: inches' }, formRef: 'Part 8 · Item 3 · Inches', options: [...Array(12)].map((_, i) => ({ value: String(i), label: { es: String(i), en: String(i) } })) },
            { id: 'weight', type: 'number', required: true, label: { es: 'Peso en libras', en: 'Weight in pounds' }, formRef: 'Part 8 · Item 4', maxLength: 3 },
            {
              id: 'eyes',
              type: 'select',
              required: true,
              label: { es: 'Color de ojos', en: 'Eye color' },
              formRef: 'Part 8 · Item 5',
              options: [
                { value: 'BN', label: t('Café', 'Brown') },
                { value: 'BL', label: t('Negro', 'Black') },
                { value: 'HA', label: t('Avellana (hazel)', 'Hazel') },
                { value: 'GN', label: t('Verde', 'Green') },
                { value: 'BU', label: t('Azul', 'Blue') },
                { value: 'GR', label: t('Gris', 'Gray') },
                { value: 'MA', label: t('Granate', 'Maroon') },
                { value: 'PN', label: t('Rosado', 'Pink') },
                { value: 'UN', label: t('Desconocido u otro', 'Unknown / Other') },
              ],
            },
            {
              id: 'hair',
              type: 'select',
              required: true,
              label: { es: 'Color de cabello', en: 'Hair color' },
              formRef: 'Part 8 · Item 6',
              options: [
                { value: 'BL', label: t('Negro', 'Black') },
                { value: 'BR', label: t('Café', 'Brown') },
                { value: 'BN', label: t('Rubio', 'Blond') },
                { value: 'GR', label: t('Gris', 'Gray') },
                { value: 'WH', label: t('Blanco', 'White') },
                { value: 'RD', label: t('Rojo', 'Red') },
                { value: 'SA', label: t('Rubio rojizo (sandy)', 'Sandy') },
                { value: 'NH', label: t('Calvo/a (sin cabello)', 'Bald (no hair)') },
                { value: 'OT', label: t('Desconocido u otro', 'Unknown / Other') },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'eligibility',
      part: 'Part 9',
      title: t('Elegibilidad', 'Eligibility'),
      questions: [
        ...P9_GROUPS.flatMap((g, gi): Question[] => [
          {
            id: `p9.${g.id}`,
            kind: 'yesNoList',
            formRef: `Part 9 · Items ${g.items[0].item}–${g.items[g.items.length - 1].item}`,
            question: g.title,
            why: g.why ?? t('"Alguna vez" significa en cualquier momento y en cualquier país.', '"Ever" means at any time, anywhere in the world.'),
            ...(gi === 0 || g.id === 'crimes' ? { notice: legal } : {}),
            items: toYesNoItems(g.items),
          },
          ...(g.id === 'organizations'
            ? [
                {
                  id: 'org1',
                  kind: 'fields',
                  formRef: 'Part 9 · Items 2–5 · Organization 1',
                  showIf: is('p9.1', 'yes'),
                  question: t('Sobre esa organización', 'About that organization'),
                  why: t('Si fue miembro de más de una, escriba las demás a mano en la Parte 14.', 'If you were in more than one, write the others by hand in Part 14.'),
                  fields: [
                    { id: 'org1.name', type: 'text', required: true, label: { es: 'Nombre de la organización', en: 'Name of organization' }, formRef: 'Part 9 · Item 2' },
                    { id: 'org1.city', type: 'text', label: { es: 'Ciudad', en: 'City' }, formRef: 'Part 9 · Item 3 · City or Town' },
                    { id: 'org1.state', type: 'text', label: { es: 'Estado o provincia', en: 'State or province' }, formRef: 'Part 9 · Item 3 · State or Province' },
                    { id: 'org1.country', type: 'text', label: { es: 'País', en: 'Country' }, formRef: 'Part 9 · Item 3 · Country' },
                    { id: 'org1.nature', type: 'text', required: true, label: { es: '¿Qué hace la organización? (en inglés)', en: 'Nature of the organization' }, formRef: 'Part 9 · Item 4 · Nature of Organization' },
                    { id: 'org1.involvement', type: 'text', required: true, label: { es: '¿Qué hacía usted en ella? (en inglés)', en: 'Nature of your involvement' }, formRef: 'Part 9 · Item 4 · Nature of involvement' },
                    date('org1.from', 'Desde', 'From', 'Part 9 · Item 5 · From', false),
                    date('org1.to', 'Hasta', 'To', 'Part 9 · Item 5 · To', false),
                  ],
                } as Question,
              ]
            : []),
          ...(g.id === 'misc'
            ? [
                {
                  id: 'draftStatus',
                  kind: 'fields',
                  formRef: 'Part 9 · Item 84',
                  showIf: is('p9.83', 'yes'),
                  question: t('¿Cuál era su estatus justo antes de salir?', 'What was your status right before you left?'),
                  fields: [{ id: 'draft.status', type: 'text', required: true, label: { es: 'Nacionalidad o estatus migratorio', en: 'Nationality or immigration status' }, formRef: 'Part 9 · Item 84' }],
                } as Question,
              ]
            : []),
        ]),
        {
          id: 'publicCharge.exemption',
          kind: 'choice',
          formRef: 'Part 9 · Item 56 · Public Charge',
          question: t('¿Está exento/a de la regla de "carga pública"?', 'Are you exempt from the public charge rule?'),
          why: t(
            'La mayoría de los casos familiares NO están exentos. Si su categoría no está en la lista, elija la primera opción y responda las preguntas de ingresos.',
            'Most family cases are NOT exempt. If your category isn’t listed, choose the first option and answer the income questions.',
          ),
          options: [
            { value: NOT_EXEMPT, label: t('No estoy en ninguna categoría exenta', 'I do not fall under any of the exempt categories') },
            ...PUBLIC_CHARGE_EXEMPTIONS.map((e) => ({ value: e.value, label: { es: e.es, en: e.en } })),
          ],
        },
        {
          id: 'publicCharge.household',
          kind: 'fields',
          formRef: 'Part 9 · Items 57, 61–62',
          showIf: notExempt,
          question: t('Su hogar, sus estudios y sus habilidades', 'Your household, education and skills'),
          fields: [
            { id: 'pc.household', type: 'text', required: true, label: { es: 'Tamaño de su hogar (en inglés, por ejemplo "household of 3")', en: 'Family status (for example, household size)' }, formRef: 'Part 9 · Item 57', placeholder: 'Household of 3' },
            {
              id: 'pc.education',
              type: 'select',
              required: true,
              label: { es: 'Nivel de estudios más alto', en: 'Highest level of education' },
              formRef: 'Part 9 · Item 61',
              options: [
                { value: 'C', label: t('Menos que secundaria (high school)', 'Less than a high school diploma') },
                { value: '2', label: t('Secundaria, GED o equivalente', 'High school diploma, GED, or alternative credential') },
                { value: '1', label: t('Un año o más de universidad, sin título', '1 or more years of college credit, no degree') },
                { value: '3', label: t('Título técnico (associate)', 'Associate’s degree') },
                { value: '7', label: t('Licenciatura (bachelor)', 'Bachelor’s degree') },
                { value: '4', label: t('Maestría', 'Master’s degree') },
                { value: '5', label: t('Título profesional (JD, MD…)', 'Professional degree (JD, MD, DMD, etc.)') },
                { value: '6', label: t('Doctorado', 'Doctorate degree') },
              ],
            },
            { id: 'pc.grade', type: 'text', label: { es: 'Si no terminó secundaria: último grado que completó', en: 'If less than high school: highest grade completed' }, formRef: 'Part 9 · Item 61' },
            { id: 'pc.skills', type: 'longText', label: { es: 'Sus habilidades, certificados y licencias (una por línea, en inglés)', en: 'Your skills, certifications and licenses (one per line)' }, formRef: 'Part 9 · Item 62 · List of Certifications', hint: t('Por ejemplo: "Commercial driver’s license", "Forklift certification". Caben 8 líneas.', 'For example: "Commercial driver’s license". 8 lines fit.') },
          ],
        },
        ranges('pc.income', 'Part 9 · Item 58 · Annual household income', '¿Cuál es el ingreso anual de su hogar?', 'What is your annual household income?', ['$0-27,000', '$27,001-52,000', '$52,001-85,000', '$85,001-141,000', 'Over $141,000']),
        ranges('pc.assets', 'Part 9 · Item 59 · Total value of household assets', '¿Cuánto valen en total los bienes de su hogar?', 'What is the total value of your household assets?', ['$0-18,400', '$18,401-136,000', '$136,001-321,400', '$321,401-707,100', 'Over $707,100']),
        ranges('pc.liabilities', 'Part 9 · Item 60 · Total value of household liabilities', '¿Cuánto deben en total en su hogar?', 'What is the total value of your household liabilities?', ['$0', '$1-10,100', '$10,101-57,700', '$57,701-186,800', 'Over $186,800']),
        {
          id: 'pc.benefits',
          kind: 'choice',
          formRef: 'Part 9 · Item 63 · Have you ever received any means-tested public benefit?',
          showIf: notExempt,
          question: t('¿Alguna vez ha recibido un beneficio público basado en ingresos?', 'Have you ever received a means-tested public benefit?'),
          why: t('Por ejemplo: dinero en efectivo de asistencia (SSI, TANF) o cuidado a largo plazo pagado por el gobierno.', 'For example: cash assistance (SSI, TANF) or government-funded long-term care.'),
          options: yesNo,
        },
        ...[1, 2, 3, 4].map(
          (r): Question => ({
            id: `pc.benefit${r}`,
            kind: 'fields',
            formRef: `Part 9 · Item 64 (row ${r})`,
            showIf: (a) => notExempt(a) && a['pc.benefits'] === 'yes' && (r === 1 || a[`pc.benefit.more${r - 1}`] === 'yes'),
            question: r === 1 ? t('¿Qué beneficio recibió?', 'Which benefit did you receive?') : t('El siguiente beneficio', 'The next benefit'),
            fields: [
              { id: `pc.benefit${r}.name`, type: 'text', required: true, label: { es: 'Beneficio (en inglés)', en: 'Benefit' }, formRef: `Part 9 · Item 64 (row ${r}) · Means-Tested Public Benefit Received`, placeholder: 'SSI' },
              date(`pc.benefit${r}.start`, 'Inicio', 'Start date', `Part 9 · Item 64 (row ${r}) · Start Date`),
              date(`pc.benefit${r}.end`, 'Fin', 'End date', `Part 9 · Item 64 (row ${r}) · End Date`, false),
              { id: `pc.benefit${r}.amount`, type: 'text', label: { es: 'Monto en dólares', en: 'Dollar amount' }, formRef: `Part 9 · Item 64 (row ${r}) · Dollar Amount` },
              { id: `pc.benefit${r}.reason`, type: 'text', label: { es: 'Razón', en: 'Reason' }, formRef: `Part 9 · Item 64 (row ${r}) · Reason` },
              ...(r < 4 ? [{ id: `pc.benefit.more${r}`, type: 'select', required: true, label: { es: '¿Recibió otro beneficio?', en: 'Did you receive another benefit?' }, formRef: 'Part 9 · Item 64', options: yesNo } as Field] : []),
            ],
          }),
        ),
        ...P9_ITEMS.filter((it) => it.explain).map(
          (it): Question => ({
            id: `explain.${it.item}`,
            kind: 'fields',
            formRef: `Part 14 · Additional Information (Part 9, Item ${it.item})`,
            showIf: (a) => a[`p9.${it.item}`] === 'yes',
            question: t(`Explique su respuesta a la pregunta ${it.item}`, `Explain your answer to question ${it.item}`),
            why: t(
              'Diga qué pasó, cuándo y dónde, en inglés. Para delitos: qué fue, dónde, el resultado y la sentencia. Las primeras 4 explicaciones se escriben en la Parte 14 del PDF.',
              'Say what happened, when and where, in English. For crimes: what, where, the outcome and the sentence. The first 4 explanations go in Part 14 of the PDF.',
            ),
            notice: legal,
            fields: [
              {
                id: `explain.${it.item}.text`,
                type: 'longText',
                required: true,
                label: { es: 'Explicación (en inglés)', en: 'Explanation' },
                formRef: `Part 14 · Page ${explainPage(it.item)}, Part 9, Item ${it.item}`,
                maxLength: 450,
              },
            ],
          }),
        ),
      ],
    },
    {
      id: 'contact',
      part: 'Part 10',
      title: t('Contacto', 'Contact'),
      questions: [
        {
          id: 'contactInfo',
          kind: 'fields',
          formRef: 'Part 10 · Items 1–3 · Applicant’s Contact Information',
          question: t('¿Cómo puede contactarle USCIS?', 'How can USCIS contact you?'),
          fields: [
            { id: 'phone', type: 'phone', required: true, label: { es: 'Teléfono de día', en: 'Daytime phone' }, formRef: 'Part 10 · Item 1', placeholder: '213 555 0123' },
            { id: 'mobile', type: 'phone', label: { es: 'Celular', en: 'Mobile phone' }, formRef: 'Part 10 · Item 2' },
            { id: 'email', type: 'email', label: { es: 'Correo electrónico', en: 'Email' }, formRef: 'Part 10 · Item 3', maxLength: 38 },
          ],
        },
      ],
    },
  ],
};

export { flaggedI485 };
